config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  resources :products, only: :index do
    resources :comments, only: :index
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :mentions, dependent: :destroy
  has_many :comments, through: :mentions
  has_many :specification_feeds

  def update_spec
    feeds_data = self.specification_feeds.map{|feed| ["#{feed.source}_data".to_sym, feed.data] }.to_h
    update_attributes( Specification.new(feeds_data).extract )
  end

  def update_price
    amazon_api_feed = specification_feeds.where(source: 'amazon_api').first
    amazon_api_feed.refresh
    update_attributes(price_in_cents: amazon_api_feed['data']['price'], price_updated_at: amazon_api_feed.updated_at) if amazon_api_feed['data']['price'].present?
  end

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @mentions_count = Mention.count

    @products = ProductFilter.new.filter_by(filter_params.merge(params.slice('after')))
    @attr_distr = AttributesDistribution.new(@products, filter_params).calculate

    @products = @products.paginate(page: params[:page], per_page: 25)

  end

  private 

  def filter_params
    params.slice(*Specification.filter_params.values.flatten)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def specification_filters(distribution, params)
    %i(price brand display_size display_resolution ram_size hdd_type hdd_size processor operating_system ).map do |spec_param|
      SpecificationFilter.new(spec_param, distribution[spec_param], params).html
    end.join.html_safe
  end
end

app/views/products/_product.html.erb
<li>
  <p class="item"><%= link_to product.title, product.offer_url %></p>
  <p class="item-info">
  Price: <%= product.price_in_cents.nil? ? "N/A" : "$#{product.price_in_cents/100.to_f}" %> <%= "(as of #{product.price_updated_at.strftime("%b %e, %Y %H:%M %Z")})" if product.price_updated_at.present? %>, 
    <%= link_to("#{product.mentions_count} mentions", product_comments_path(product, after: params[:after])) %>
  </p>
</li>

app/views/products/index.html.erb
<% content_for :title do %>
  LaptopHits.com - Find out what laptops people recommend.
<% end %>

<% content_for :header do %>
<h1><%= link_to "LaptopHits.com", root_path %></h1>
<div class="tagline">
  <h2>See what laptops people recommend these days. </h2>
  <p>Based on <%= @mentions_count %> laptop mentions on Reddit</p>
</div>
<% end %>

<% content_for :sidebar do %>
<%= link_to "Clear all filters", products_path %>
<h4>Time: </h4>
<ul>
  <li><%= link_to_unless params[:after].nil?, "All time", products_path(params.except(:controller, :action, :page).merge({after: nil})) %></li>
  <li><%= link_to_unless params[:after] == "1w", "Past week", products_path(params.except(:controller, :action, :page).merge({after: "1w"})) %></li>
  <li><%= link_to_unless params[:after] == "1m", "Past month", products_path(params.except(:controller, :action, :page).merge({after: "1m"})) %></li>
  <li><%= link_to_unless params[:after] == "1y", "Past year", products_path(params.except(:controller, :action, :page).merge({after: "1y"})) %></li>
</ul>

<%= specification_filters(@attr_distr, params) %>
<% end %>

<h3>Recommended laptops</h3>
<% if @products.length == 0 %>
  <em>Sorry, there are no results matching your criteria.</em>
<% else %>
  <%= link_to "Filters", "#", class: 'mobile-filter' %>

  <ol start="<%= (params[:page].to_i <= 1 ? 0 : params[:page].to_i - 1)*25 + 1%>">
    <%= render partial: "product", collection: @products %>
  </ol>
  <%= will_paginate @products %>
<% end %>